"""Add linkedin column to leads

Revision ID: fa38e0bb86f0
Revises: f7a681aa6786
Create Date: 2026-03-17 22:32:42.444908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa38e0bb86f0'
down_revision: Union[str, Sequence[str], None] = 'f7a681aa6786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('linkedin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'linkedin')
    # ### end Alembic commands ###
